wget http://radcircle.com/images/assets/profiles/aj100circle.png
wget http://radcircle.com/images/assets/profiles/alec100circle.png
wget http://radcircle.com/images/assets/profiles/alysha100circle.png
wget http://radcircle.com/images/assets/profiles/anita100circle.png
wget http://radcircle.com/images/assets/profiles/ashlee100circle.png
wget http://radcircle.com/images/assets/profiles/alec100circle.png 
wget http://radcircle.com/images/assets/profiles/austinmartin100circle.png
wget http://radcircle.com/images/assets/profiles/brandon100circle.png
wget http://radcircle.com/images/assets/profiles/charlotte100circle.png
wget http://radcircle.com/images/assets/profiles/connor100circle.png
wget http://radcircle.com/images/assets/profiles/filippo100circle.png
wget http://radcircle.com/images/assets/profiles/gavin100circle.png
wget http://radcircle.com/images/assets/profiles/jennifer100circle.png
wget http://radcircle.com/images/assets/profiles/katie100circle.png
wget http://radcircle.com/images/assets/profiles/madison100circle.png
wget http://radcircle.com/images/assets/profiles/marcos100circle.png
wget http://radcircle.com/images/assets/profiles/michelle-s100circle.png
wget http://radcircle.com/images/assets/profiles/sandra100circle.png
wget http://radcircle.com/images/assets/profiles/shannon100circle.png